version: 2
registries:
  python-index-pypi-org-simple:
    type: python-index
    url: https://pypi.org/simple/
    username: "${{secrets.PYTHON_INDEX_PYPI_ORG_SIMPLE_USERNAME}}"
    password: "${{secrets.PYTHON_INDEX_PYPI_ORG_SIMPLE_PASSWORD}}"

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: astroid
    versions:
    - 2.5.1
    - 2.5.2
    - 2.5.3
  registries:
  - python-index-pypi-org-simple
