# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR testyboi

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: run main ting
      run: |
        ./main.sh
    
    - name: output la data
      run: |
        for i in `echo docs/output/*`; do echo "$i"; echo; cat $i; echo; echo; done
    
    - name: Get git status
      run: |
        echo "GIT_STATUS=$(git status)" >> $GITHUB_ENV

    - name: Comment on PR - git status
      uses: thollander/actions-comment-pull-request@master
      with:
        message: |
          Git Status: 
          ${{ env.GIT_STATUS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Get git diff
      run: |
        echo "GIT_DIFF=${git diff}" >> $GITHUB_ENV

    - name: Comment on PR - git diff
      uses: thollander/actions-comment-pull-request@master
      with:
        message: |
          Git Diff: 
          ${{ env.GIT_DIFF }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
